models.py
from django.db import models
from django.contrib.auth.models import User
from django.forms import ModelForm
#from django.db.models.signals import post_save

# Student Class relates default user model

class UserProfile(models.Model):
    user = models.OneToOneField(User,blank=True,related_name='colleger')
    first_name = models.CharField(max_length=32, null=True, blank=True)
    last_name = models.CharField(max_length=32, null=True, blank=True)
    mobile = models.CharField(max_length=12, null=True, blank=True)
    
    @property
    def is_student(self):
        try:
            self.student
            return True
        except Student.DoesNotExist:
            return False
    
class Address(models.Model):
    website = models.CharField(max_length=32, null=True, blank=True)
    blog = models.CharField(max_length=32, null=True, blank=True)
    address_line1 = models.CharField(max_length=32, null=True, blank=True)
    address_line2 = models.CharField(max_length=32, null=True, blank=True)
    address_line3 = models.CharField(max_length=32, null=True, blank=True)
    pincode = models.CharField(max_length=6,null=True, blank=True)
    area = models.CharField(max_length=32,null=True, blank=True)
    city = models.CharField(max_length=32,null=True, blank=True)
    state = models.CharField(max_length=32,null=True, blank=True)
    country = models.CharField(max_length=24,null=True, blank=True)
    phone = models.CharField(max_length=16,null=True, blank=True)
    
class College(models.Model):
    AFFILIATION = (
        ('anna_univ', 'Anna University'),
        ('deemed', 'Deemed'),
        ('autonomous', 'Autonomous'),
    )
    TYPE = (
        ('govt', 'Government'),
        ('govt_aid', 'Government-Aided'),
        ('private', 'Private'),
    )
    address = models.ForeignKey(Address,blank=True, null=True)
    name = models.CharField(max_length=64)
    ugc_cgpa = models.CharField(max_length=16, null=True, blank=True)
    ugc_grade = models.CharField(max_length=16, null=True, blank=True)
    established = models.CharField(max_length=16, null=True, blank=True)
    faculties = models.CharField(max_length=4, null=True, blank=True)
    affiliation = models.CharField(max_length=12, choices=AFFILIATION, null=True, blank=True)
    type = models.CharField(max_length=12, choices=TYPE, null=True, blank=True)
    
    def __unicode__(self):
        return u'%s' % (self.name)
    
class Skill(models.Model):
    SKILLS = (
        ('c', 'C'),
        ('cpp', 'C++'),
        ('vb', 'VB'),
        ('java', 'JAVA'),
    )
    TYPES = (
        ('soft', 'Soft-Skills'),
        ('it', 'IT-Skills'),
    )
    skill = models.CharField(max_length=8, choices=SKILLS, null=True, blank=True)
    skill_type = models.CharField(max_length=8, choices=TYPES, null=True, blank=True)

class Student(UserProfile):
    student = models.OneToOneField(UserProfile,related_name='student')
    skills = models.ManyToManyField(Skill, through='SkillSet')
    study = models.ManyToManyField(College, through='Education')
    address = models.ForeignKey(Address,blank=True, null=True)
    passport = models.CharField(max_length=16, null=True, blank=True)
    resume = models.FileField(upload_to='resumes/%Y/%m/%d')
    dob = models.DateTimeField(null=True, blank=True)
    #avatar = models.FileField()
    #profile_photo = models.FileField()
    #tenth_certificate = models.FileField()
    #hsc_certificate = models.FileField()
    tenth_percentage = models.CharField(max_length=5, null=True, blank=True)
    hsc_percentage = models.CharField(max_length=5, null=True, blank=True)
 
class Professor(UserProfile):
    professor = models.OneToOneField(UserProfile,related_name='professor')
    working = models.ManyToManyField(College, through='Teaching', blank=True) 
    address = models.ForeignKey(Address,blank=True, null=True)
    prof_id = models.CharField(max_length=24, null=True, blank=True)

class Education(models.Model):
    YEAR_IN = (
        ('1', 'First Year'),
        ('2', 'Second Year'),
        ('3', 'Third Year'),
        ('4', 'Fourth Year'),
    )
    BRANCHES = (
        ('aero', 'Aeronautics'),
        ('auto', 'Automobile'),
        ('cs', 'Computer Science'),
        ('civ', 'Civil'),
        ('eee', 'Electrical and Electronics'),
        ('ece', 'Electronics and Communication'),
        ('it', 'Information Technology'),
        ('mech', 'Mechanical'),
        ('mecht', 'Mechatronics'),
    )
    college = models.ForeignKey(College, null=True, blank=True)
    student = models.ForeignKey(Student, null=True, blank=True)
    roll_no = models.CharField(max_length=24, null=True, blank=True)
    register_no = models.CharField(max_length=24, null=True, blank=True)
    doj = models.CharField(max_length=4, null=True, blank=True)
    dop = models.CharField(max_length=4, null=True, blank=True)
    year = models.CharField(max_length=2, choices=YEAR_IN, null=True, blank=True)
    branch = models.CharField(max_length=8, choices=BRANCHES, null=True, blank=True)
    
class SkillSet(models.Model):
    RATING = (
        ('beginner', 'Beginner'),
        ('learner', 'Learner'),
        ('intermediate', 'Intermediate'),
        ('expert', 'Expert'),
    )
    skill = models.ForeignKey(Skill)
    student = models.ForeignKey(Student)
    rating = models.CharField(max_length=8, choices=RATING, null=True, blank=True)
    best_score = models.CharField(max_length=8, choices=RATING, null=True, blank=True)
    last_score = models.CharField(max_length=8, choices=RATING, null=True, blank=True)
    
class Teaching(models.Model):
    BRANCHES = (
        ('aero', 'Aeronautics'),
        ('auto', 'Automobile'),
        ('cs', 'Computer Science'),
        ('civ', 'Civil'),
        ('eee', 'Electrical and Electronics'),
        ('ece', 'Electronics and Communication'),
        ('it', 'Information Technology'),
        ('mech', 'Mechanical'),
        ('mecht', 'Mechatronics'),
    )
    SUBJECTS = (
        ('maths', 'Maths'),
        ('ed', 'Engineering Drawing'),
        ('atd', 'Applied Thermodynamics'),
        ('pe', 'Power Electronics'),
    )
    college = models.ForeignKey(College)
    professor = models.ForeignKey(Professor)
    date_of_joining = models.DateTimeField(null=True, blank=True)
    date_left = models.DateTimeField(null=True, blank=True)
    subject = models.CharField(max_length=2, choices=SUBJECTS, null=True, blank=True)
    branch = models.CharField(max_length=8, choices=BRANCHES, null=True, blank=True)
    
class Company(models.Model):
    address = models.ForeignKey(Address, blank=True, null=True)
    name = models.CharField(max_length=48)
    head_count = models.CharField(max_length=8, blank=True, null=True)
    revenue = models.CharField(max_length=12, blank=True, null=True)
    head_quarters = models.CharField(max_length=64)  
    
class Employer(UserProfile):
    employer = models.OneToOneField(UserProfile,related_name='employer') 
    address = models.ForeignKey(Address,blank=True, null=True)
    emp_id = models.CharField(max_length=24, null=True, blank=True)
    company = models.ForeignKey(Company, null=True, blank=True)

forms.py
from django.forms import ModelForm
from django import forms
from siteprofiles.models import *
          
class AddressForm(forms.ModelForm):
    class Meta:
        model = Address
        
class EmployerForm(forms.ModelForm):
    class Meta:
        model = Employer
        exclude = ('employer','address','user',)
  
class ProfessorForm(forms.ModelForm):
    class Meta:
        model = Professor
        exclude = ('professor','address','user',)
   
class CollegeForm(forms.ModelForm):
    class Meta:
        model = College
        exclude = ('address',)
        
class StudentForm(forms.ModelForm):
    dob = forms.DateField(('%d/%m/%Y',), label='Date of Birth', required=False,  
        widget=forms.DateTimeInput(format='%d/%m/%Y', attrs={
            'class':'input',
            'readonly':'readonly',
            'size':'15'
        })
    )
    resume = forms.FileField(
        label='Select a file to upload',
        help_text='max. 42 megabytes'
    )
    class Meta:
        model = Student
        exclude = ('student','user','skills','address','study')

templates/add_college.html
{% extends "base.html" %}
{% block title %}Edit Profile{% endblock %}
 
{% block content %}
<h1>Add College</h1>
    <div class="tabcontent" style="display:block">
        <form method="post" action="" class="accountForm marginTop">{% csrf_token %}<!-- Added due to internal url-->
        	<input type="submit" name="submit" value="{{ crud }} College" class="submit" style="width:100px;margin:0px auto;height:32px;display:inline-block;">
		   <div class="college-profile" style="width:400px;background-color:#aaa;margin-top:30px;margin-left:50px;float:left;">
		   <h3>College Details</h3>
			{% for field in form %}
			<div style="width:400px;padding:15px;">
		            <div class="hint {%if field.field.required %} bold {% endif %}" style="clear:both;width:40%;display:inline-block">{{ field.label_tag }}</div>
					<div style="display:inline">{{ field }}</div>
			</div>
					{% if field.help_text %}<span>{{ field.help_text }}</span>{% endif %}
					{% if field.errors %}<span>{{ field.errors }}</span>{% endif %}
			{% endfor %}
			</div>
			<div class="student-profile" style="width:400px;background-color:#aaa;margin-top:30px;margin-left:50px;float:left">
			<h3>Contact Details</h3>
			{% for field in addr_form %}
			<div style="width:400px;padding:15px;">
		            <div class="hint {%if field.field.required %} bold {% endif %}" style="clear:both;width:40%;display:inline-block">{{ field.label_tag }}</div>
					<div style="display:inline">{{ field }}</div>
			</div>
					{% if field.help_text %}<span>{{ field.help_text }}</span>{% endif %}
					{% if field.errors %}<span>{{ field.errors }}</span>{% endif %}
			{% endfor %}
			</div>
		</form>
    </div>
{% endblock content %}

templates/base.html
{% load i18n %}
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">

<head>
    <link rel="stylesheet" href="/style.css" />
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.8.0/jquery.min.js" type="text/javascript"></script>
    <script src="http://code.jquery.com/ui/1.9.0/jquery-ui.js"></script>
    <link rel="stylesheet" href="http://code.jquery.com/ui/1.9.0/themes/base/jquery-ui.css" />
    <title>{% block title %}User test{% endblock %}</title>
    	<style type="text/css">
    	div.tabscontainer{
		    margin:15px 0px;
		}
		div.profile-content {
			display: block;
			width:400px;
			padding:10px;
		}
		
		div.profile-field-label {
			width:120px;
			padding:5px;
			display:inline-block
		}
		 
		div.profile-field-value {
			width:250px;
			display:inline-block;
			padding:5px;
		}
		
		div.tabscontainer div.tabs{
		    list-style: none;
		    width: 160px;
		    cursor: pointer;
		    float:left;
		    margin-top: 150px;
		    margin-left: 600px;
		    z-index: 2;
		}
		 
		div.tabscontainer div.curvedContainer{
		    margin-left: 159px;
		    border:1px solid #7c7c77;
		    min-height:400px;
		    -moz-border-radius: 13px;
		    border-radius: 13px;
		}
		 
		div.tabscontainer div.curvedContainer .tabcontent{
		    display:none;
		    padding:20px;
		    font-size:12px;
		    font-family: "CenturyGothicRegular", "Century Gothic", Arial, Helvetica, sans-serif;
		}
		 
		div.tabs div.tab{
		    display: block;
		    height: 48px;
		    background: #eeeeea;
		    border: #d6d6d2 solid 1px;
		    border-top: none;
		    position: relative;
		    color: #73736b;
		}
		 
		div.tabs div.link{
		    padding-left: 20px;
		    padding-top:20px;
		    font-family: "CenturyGothicRegular", "Century Gothic", Arial, Helvetica, sans-serif;
		    font-size: 14px;
		}
		 
		div.tabs div.tab.selected{
		    border-right-color: #aeaeaa;
		}
		 
		div.tabs div.tab.selected{
		    background: url(menuSelBack.png) repeat-x;
		    border-right-color: #7c7c77;
		}
		 
		div.tabs div.tab.first{
		    border-top: #dbdbb7 solid 1px;
		    -moz-border-radius-topleft: 13px;
		    border-top-left-radius: 13px;
		}
		 
		div.tabs div.tab.last{
		    -moz-border-radius-bottomleft: 13px;
		    border-bottom-left-radius: 13px;
		}
		 
		div.tabs div.tab div.arrow{
		    position: absolute;
		    background: url(homeSelArrow.png) no-repeat;
		    height: 58px;
		    width: 17px;
		    left: 100%;
		    top: 0px;
		    display: none;
		}
		 
		div.tabs div.tab.selected div.arrow{
		    display: block;
		}
		</style>
		
		<script type="text/javascript">
		$(document).ready(function() {
	    	$(".tabs .tab[id^=tab_menu]").click(function() {
	        var curMenu=$(this);
	        $(".tabs .tab[id^=tab_menu]").removeClass("selected");
	        curMenu.addClass("selected");
	 
	        var index=curMenu.attr("id").split("tab_menu_")[1];
	        $(".curvedContainer .tabcontent").css("display","none");
	        $(".curvedContainer #tab_content_"+index).css("display","block");
	   		});
	   		$(function() {
           		$("#id_dob").datepicker({ dateFormat: 'dd/mm/yy' });
        	});
		});
		</script>
</head>

<body>
    <div id="header"style="width:100%;height:50px">
        {% block header %}
	{% if user.is_authenticated %}
	{% trans "Logged in" %}: {{ user.username }} 
	(<a href="{% url auth_logout %}">{% trans "Log out" %}</a> | 
	<a href="{% url auth_password_change %}">{% trans "Change password" %}</a>)
	{% else %}
	<div id="login-form" style="float:right;padding:10px">
	<form action="/login/" method="post" accept-charset="utf-8">{% csrf_token %}
		<label for="username">Username</label><input type="text" name="username" value="" id="username" />
		<label for="password">Password</label><input type="password" name="password" value="" id="password" />
		<input type="submit" value="Login">
	</form>
	</div>
	{% endif %}
        {% endblock %}
    </div>
	<div id="navigation">
        {% block navigation %}{% endblock %}
    </div>
    <div id="content">
        {% block content %}{% endblock %}
    </div>

    <div id="footer">
        {% block footer %}
        {% endblock %}
    </div>
</body>

</html>

templates/college_detail.html
{% extends "base.html" %}
{% block title %}Edit College Details{% endblock %}
{% block navigation %}
	<a href="/colleges/edit/{{college.id}}">Edit College Details</a>
{% endblock navigation %}
{% block content %}
    <div class="profile-content">
    <h3> {{ college.name }}'s Details</h3>
    	<div class="profile-field-label">Name: </div>
		<div class="profile-field-value">{{ college.name }}</div>
		<div class="profile-field-label">Established:</div>
		<div class="profile-field-value">{{ college.established }}</div>
		<div class="profile-field-label">Faculties:</div>
		<div class="profile-field-value">{{ college.faculties }}</div>
		<div class="profile-field-label">Affiliation:</div>
		<div class="profile-field-value">{{ college.affiliation }}</div>
		<div class="profile-field-label">College Funding:</div>
		<div class="profile-field-value">{{ college.type }}</div>
		<div class="profile-field-label">UPC CGPA:</div>
		<div class="profile-field-value">{{ college.ugc_cgpa }}</div>
		<div class="profile-field-label">UPC GRADE:</div>
		<div class="profile-field-value">{{ college.ugc_grade }}</div>
	<h3>Contact Details</h3>
		<div class="profile-field-label">Address Line 1:</div>
		<div class="profile-field-value">{{ addr.address_line1 }}</div>
		<div class="profile-field-label">Address Line 2:</div>
		<div class="profile-field-value">{{ addr.address_line2 }}</div>
		<div class="profile-field-label">Address Line 3:</div>
		<div class="profile-field-value">{{ addr.address_line3 }}</div>
		<div class="profile-field-label">Area:</div>
		<div class="profile-field-value">{{ addr.area }}</div>
		<div class="profile-field-label">City:</div>
		<div class="profile-field-value">{{ addr.city }}</div>
		<div class="profile-field-label">State:</div>
		<div class="profile-field-value">{{ addr.state }}</div>
		<div class="profile-field-label">Country:</div>
		<div class="profile-field-value">{{ addr.country }}</div>
		<div class="profile-field-label">Pincode:</div>
		<div class="profile-field-value">{{ addr.pincode }}</div>
		<div class="profile-field-label">Phone:</div>
		<div class="profile-field-value">{{ addr.phone }}</div>
		<div class="profile-field-label">Website:</div>
		<div class="profile-field-value">{{ addr.website }}</div>
		<div class="profile-field-label">Blog:</div>
		<div class="profile-field-value">{{ addr.blog }}</div>
	</div>
{% endblock content %}

templates/edit_profile.html
{% extends "base.html" %}
{% block title %}Edit Profile{% endblock %}
 
{% block content %}
<h1>Edit Profile for {{ user }}</h1>
    <div class="tabcontent" style="display:block">
        <form method="post" enctype="multipart/form-data" action="" class="accountForm marginTop">{% csrf_token %}<!-- Added due to internal url-->
        		<input type="hidden" name="persontype" value="student"/>
		<input type="submit" name="submit" value="Update" class="submit" style="width:100px;margin:0px auto;display:inline-block;height:32px;">
		   <div class="student-profile" style="width:400px;background-color:#aaa;margin-top:30px;margin-left:50px;float:left">
		   <h3>Personal Info</h3>
			{% for field in form %}
			<div style="width:400px;padding:15px;">
		            <div class="hint {%if field.field.required %} bold {% endif %}" style="clear:both;width:40%;display:inline-block">{{ field.label_tag }}</div>
					<div style="display:inline">{{ field }}</div>
			</div>
					{% if field.help_text %}<span>{{ field.help_text }}</span>{% endif %}
					{% if field.errors %}<span>{{ field.errors }}</span>{% endif %}
			{% endfor %}
			</div>
			<div class="student-profile" style="width:400px;background-color:#aaa;margin-top:30px;margin-left:50px;float:left">
			<h3>Contact Details</h3>
			{% for field in addr_form %}
			<div style="width:400px;padding:15px;">
		            <div class="hint {%if field.field.required %} bold {% endif %}" style="clear:both;width:40%;display:inline-block">{{ field.label_tag }}</div>
					<div style="display:inline">{{ field }}</div>
			</div>
					{% if field.help_text %}<span>{{ field.help_text }}</span>{% endif %}
					{% if field.errors %}<span>{{ field.errors }}</span>{% endif %}
			{% endfor %}
			</div>
			</div>
			<fieldset>
			{{ college.management_form }}
				{% for form in college.forms %}
		        	<div>{{form.as_p}}</div>
		      	{% endfor %}
		      <input title='Add College' type='submit' name='add_college' value='Add a College' />
		    </fieldset>
		</form>
    </div>
{% endblock content %}

templates/form.html
<div class="red">
{% if form.non_field_errors %}
{{ form.non_field_errors }}
{% endif %}
</div>

<form method="post" action="" class="accountForm marginTop">{% csrf_token %}<!-- Added due to internal url-->
	<table class="" cellspacing="10">
	{% for field in form %}
		<tr>
			<td><p class="hint {%if field.field.required %} bold {% endif %}"{{ field.label_tag }}</p>
			{{ field }}</td>
				
			{% if field.help_text %}<td class="clearfix">{{ field.help_text }}</td>{% endif %}
			{% if field.errors %}<td class="myerrors clearfix">{{ field.errors }}</td>{% endif %}
		
		</tr>
	{% endfor %}
		<tr>
			<td colspan="3" >				
				<big><input type="submit" value="OK" class="big"></big>
			</td>
		</tr>
		
	</table>

</form>

templates/profile_detail.html
{% extends "base.html" %}
{% block title %}Edit Profile{% endblock %}
{% block navigation %}
	<a href="/profile/edit">Edit Profile</a>
{% endblock navigation %}
{% block content %}
    <div class="profile-content">
    <h3> {{ user }}'s Profile</h3>
    	<div class="profile-field-label">First Name: </div>
		<div class="profile-field-value">{{ st.first_name }}</div>
		<div class="profile-field-label">Last Name:</div>
		<div class="profile-field-value">{{ st.last_name }}</div>
		<div class="profile-field-label">DOB:</div>
		<div class="profile-field-value">{{ st.dob }}</div>
		<div class="profile-field-label">Resume:</div>
		<div class="profile-field-value"><a href="{{ st.resume.url }}">{{ st.resume.name }}</a></div>
		<div class="profile-field-label">Passport:</div>
		<div class="profile-field-value">{{ st.register_no }}</div>
		<div class="profile-field-label">Tenth %:</div>
		<div class="profile-field-value">{{ st.tenth_percentage }}</div>
		<div class="profile-field-label">HSC %:</div>
		<div class="profile-field-value">{{ st.hsc_percentage }}</div>
		<div class="profile-field-label">Mobile:</div>
		<div class="profile-field-value">{{ st.mobile }}</div>
	<h3>Contact</h3>
		<div class="profile-field-label">Address Line 1:</div>
		<div class="profile-field-value">{{ addr.address_line1 }}</div>
		<div class="profile-field-label">Address Line 2:</div>
		<div class="profile-field-value">{{ addr.address_line2 }}</div>
		<div class="profile-field-label">Address Line 3:</div>
		<div class="profile-field-value">{{ addr.address_line3 }}</div>
		<div class="profile-field-label">Area:</div>
		<div class="profile-field-value">{{ addr.area }}</div>
		<div class="profile-field-label">City:</div>
		<div class="profile-field-value">{{ addr.city }}</div>
		<div class="profile-field-label">State:</div>
		<div class="profile-field-value">{{ addr.state }}</div>
		<div class="profile-field-label">Country:</div>
		<div class="profile-field-value">{{ addr.country }}</div>
		<div class="profile-field-label">Pincode:</div>
		<div class="profile-field-value">{{ addr.pincode }}</div>
		<div class="profile-field-label">Phone:</div>
		<div class="profile-field-value">{{ addr.phone }}</div>
		<div class="profile-field-label">Website:</div>
		<div class="profile-field-value">{{ addr.website }}</div>
		<div class="profile-field-label">Blog:</div>
		<div class="profile-field-value">{{ addr.blog }}</div>
	<h3>Education</h3>
	{% for education in edu%}
		<h3>College Details</h3>
		<div class="profile-field-label">Register No</div>
		<div class="profile-field-value">{{ education.register_no }}</div>
		<div class="profile-field-label">Roll No</div>
		<div class="profile-field-value">{{ education.roll_no }}</div>
		<div class="profile-field-label">Current Year:</div>
		<div class="profile-field-value">{{ education.get_year_display }}</div>
		<div class="profile-field-label">Date of Joining</div>
		<div class="profile-field-value">{{ education.doj }}</div>
		<div class="profile-field-label">Date of Pass out</div>
		<div class="profile-field-value">{{ education.dop }}</div>
		<div class="profile-field-label">Branch</div>
		<div class="profile-field-value">{{ education.get_branch_display }}</div>
	{% endfor %}
	</div>
{% endblock content %}

templates/registration_base.html
<div class="red">
{% if form.non_field_errors %}
{{ form.non_field_errors }}
{% endif %}
</div>
 <div class="tabscontainer">
     <div class="tabs">
         <div class="tab selected first" id="tab_menu_1">
             <div class="link">Student</div>
             <div class="arrow"></div>
         </div>
         <div class="tab" id="tab_menu_2">
             <div class="link">Professor</div>
             <div class="arrow"></div>
         </div>
          <div class="tab last" id="tab_menu_3">
             <div class="link">Employer</div>
             <div class="arrow"></div>
         </div>
    </div>
    <div class="curvedContainer">
        <div class="tabcontent" id="tab_content_1" style="display:block">
	        <form method="post" action="/accounts/register/" class="accountForm marginTop">{% csrf_token %}<!-- Added due to internal url-->
			   <div id="student-registration" style="width:400px;background-color:#aaa;margin-top:30px;margin-left:582px">
				{% for field in form %}
				<div style="width:400px;padding:15px;">
			            <div class="hint {%if field.field.required %} bold {% endif %}" style="clear:both;width:40%;display:inline-block">{{ field.label_tag }}</div>
						<div style="display:inline">{{ field }}</div>
				</div>
						{% if field.help_text %}<span>{{ field.help_text }}</span>{% endif %}
						{% if field.errors %}<span>{{ field.errors }}</span>{% endif %}
				{% endfor %}
				<input type="hidden" name="persontype" value="student"/>
				<input type="submit" value="Register" class="submit" style="width:100px;margin:0px auto;display:block;height:32px;">
				</div>
			</form>
        </div>
        <div class="tabcontent" id="tab_content_2">
        	        <form method="post" action="/accounts/register/" class="accountForm marginTop">{% csrf_token %}<!-- Added due to internal url-->
			   <div id="student-registration" style="width:400px;background-color:#aaa;margin-top:30px;margin-left:582px">
				{% for field in form %}
				<div style="width:400px;padding:15px;">
			            <div class="hint {%if field.field.required %} bold {% endif %}" style="clear:both;width:40%;display:inline-block">{{ field.label_tag }}</div>
						<div style="display:inline">{{ field }}</div>
				</div>
						{% if field.help_text %}<span>{{ field.help_text }}</span>{% endif %}
						{% if field.errors %}<span>{{ field.errors }}</span>{% endif %}
				{% endfor %}
				<input type="hidden" name="persontype" value="professor"/>
				<input type="submit" value="Register as Professor" class="submit" style="width:140px;margin:0px auto;display:block;height:32px;">
				</div>
			</form>
        </div>
        <div class="tabcontent" id="tab_content_3">
        	        <form method="post" action="/accounts/register/" class="accountForm marginTop">{% csrf_token %}<!-- Added due to internal url-->
			   <div id="student-registration" style="width:400px;background-color:#aaa;margin-top:30px;margin-left:582px">
				{% for field in form %}
				<div style="width:400px;padding:15px;">
			            <div class="hint {%if field.field.required %} bold {% endif %}" style="clear:both;width:40%;display:inline-block">{{ field.label_tag }}</div>
						<div style="display:inline">{{ field }}</div>
				</div>
						{% if field.help_text %}<span>{{ field.help_text }}</span>{% endif %}
						{% if field.errors %}<span>{{ field.errors }}</span>{% endif %}
				{% endfor %}
				<input type="hidden" name="persontype" value="employer"/>
				<input type="submit" value="Register as Employer" class="submit" style="width:140px;margin:0px auto;display:block;height:32px;">
				</div>
			</form>
        </div>

        
        
        </div>
    </div>
</div>